project:
  type: book
  output-dir: docs

toc: true
number-sections: true
top-level-division: part
toc-depth: 3
number-depth: 4
bibliography: book.bib
csl: "ims.csl"

crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)


execute:
  freeze: auto

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

jupyter: ds24

format:
  html:
    theme: lumen
    code-block-bg: true
    code-block-border-left: true #"#31BAE9"
    # code-line-numbers: true
    highlight-style: atom-one
    page-layout: article

book:
  title: "Python/R for Data Science"
  subtitle: "Lecture notes for Fall 2024 at Arkansas Tech University"
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: "Part I: R Basic"
      chapters:
        - contents/8/intro.qmd
    # - contents/references.qmd
  sidebar:
    style: floating
    pinned: true
    align: center
    border: true
    search: true
    collapse-level: 1
    alignment: "center"
  navbar:
    subtitle: "Summer 2024"
  page-navigation: true


    



